using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;

namespace GtaCopilot.Mod
{
    /// <summary>
    /// Phase 2 state stream sender + Phase 5a reverse command reader.
    /// Owned by Claude Code; workers do not edit this file.
    ///
    /// Threading contract: the script thread only calls EnqueueLine, EnqueueAck,
    /// Status, DroppedLines, and Dispose — none of them block on network I/O.
    /// A single background thread owns the TCP connection to the brain process:
    /// it drains a bounded queue of pre-serialized JSON lines for sending AND
    /// reads inbound lines from the brain (action requests), feeding them to
    /// the ActionReceiver.
    ///
    /// Phase 5a addition: the same TCP socket is now bidirectional. After
    /// connecting, a dedicated reader thread reads newline-delimited JSON
    /// from the brain. Action lines are parsed by ActionReceiver; ack lines
    /// are written back via EnqueueAck (which feeds the send queue).
    /// </summary>
    public sealed class StateStreamClient : IDisposable
    {
        public const int BrainPort = 48651;

        private const int MaxQueuedLines = 256;
        private const int ConnectRetryIntervalMilliseconds = 2000;
        private const int SendTimeoutMilliseconds = 2000;
        private const int StopJoinTimeoutMilliseconds = 1500;

        private static readonly Encoding Utf8NoBom = new UTF8Encoding(false);

        private readonly object queueLock = new object();
        private readonly Queue<string> pendingLines = new Queue<string>();
        private readonly Thread senderThread;
        private readonly ActionReceiver actionReceiver;

        private volatile bool stopRequested;
        private volatile string status;

        // Written and read on the script thread only (inside EnqueueLine).
        private int droppedLines;

        public StateStreamClient(ActionReceiver actionReceiver)
        {
            this.actionReceiver = actionReceiver ?? throw new ArgumentNullException("actionReceiver");
            status = "waiting for brain on 127.0.0.1:" +
                BrainPort.ToString(CultureInfo.InvariantCulture);
            senderThread = new Thread(SenderLoop)
            {
                IsBackground = true,
                Name = "GtaCopilot.StateStream"
            };
            senderThread.Start();
        }

        /// <summary>Last connection status; safe to read from the script thread.</summary>
        public string Status
        {
            get { return status; }
        }

        /// <summary>Lines discarded because the queue was full. Script thread only.</summary>
        public int DroppedLines
        {
            get { return droppedLines; }
        }

        /// <summary>
        /// Called from the script thread with a fully serialized JSON line.
        /// Never blocks on the network; drops the oldest line when full.
        /// </summary>
        public void EnqueueLine(string line)
        {
            if (string.IsNullOrEmpty(line))
            {
                return;
            }

            lock (queueLock)
            {
                if (stopRequested)
                {
                    return;
                }

                while (pendingLines.Count >= MaxQueuedLines)
                {
                    pendingLines.Dequeue();
                    droppedLines++;
                }

                pendingLines.Enqueue(line);
                Monitor.Pulse(queueLock);
            }
        }

        /// <summary>
        /// Enqueue an ack line for sending back to the brain.
        /// Called from the script thread (OnTick) after executing an action,
        /// or from the reader thread for immediate refusals.
        /// </summary>
        public void EnqueueAck(string ackLine)
        {
            // Acks go through the same send queue — they're just JSON lines.
            EnqueueLine(ackLine);
        }

        public void Dispose()
        {
            lock (queueLock)
            {
                stopRequested = true;
                Monitor.PulseAll(queueLock);
            }

            // Best effort: the thread is IsBackground, so a stuck join cannot
            // keep the process alive; never abort it.
            senderThread.Join(StopJoinTimeoutMilliseconds);
        }

        private void SenderLoop()
        {
            TcpClient client = null;
            NetworkStream stream = null;
            Thread readerThread = null;
            int lastConnectAttemptTick = Environment.TickCount - ConnectRetryIntervalMilliseconds;

            while (true)
            {
                string line = WaitForNextLine();
                if (line == null)
                {
                    break;
                }

                if (stream == null)
                {
                    int now = Environment.TickCount;
                    if (unchecked(now - lastConnectAttemptTick) < ConnectRetryIntervalMilliseconds)
                    {
                        // Still backing off; this line is intentionally dropped.
                        continue;
                    }

                    lastConnectAttemptTick = now;
                    try
                    {
                        client = new TcpClient
                        {
                            NoDelay = true,
                            SendTimeout = SendTimeoutMilliseconds
                        };
                        client.Connect(IPAddress.Loopback, BrainPort);
                        stream = client.GetStream();
                        status = "connected to brain on 127.0.0.1:" +
                            BrainPort.ToString(CultureInfo.InvariantCulture);

                        // Phase 5a: start reader thread for inbound actions
                        readerThread = StartReaderThread(stream);
                    }
                    catch (Exception ex)
                    {
                        StopReaderThread(ref readerThread);
                        CloseQuietly(ref client, ref stream);
                        status = "waiting for brain (" + ex.Message + ")";
                        continue;
                    }
                }

                try
                {
                    byte[] payload = Utf8NoBom.GetBytes(line + "\n");
                    stream.Write(payload, 0, payload.Length);
                }
                catch (Exception ex)
                {
                    StopReaderThread(ref readerThread);
                    CloseQuietly(ref client, ref stream);
                    status = "disconnected (" + ex.Message + ")";
                }
            }

            StopReaderThread(ref readerThread);
            CloseQuietly(ref client, ref stream);
        }

        // ------------------------------------------------------------------
        // Phase 5a: Reader thread — reads inbound JSON lines from the brain
        // ------------------------------------------------------------------

        private Thread StartReaderThread(NetworkStream stream)
        {
            var reader = new Thread(() => ReaderLoop(stream))
            {
                IsBackground = true,
                Name = "GtaCopilot.ActionReader"
            };
            reader.Start();
            return reader;
        }

        private void StopReaderThread(ref Thread readerThread)
        {
            if (readerThread != null)
            {
                // The reader will exit when the stream is closed or an exception occurs.
                // We don't need to explicitly stop it; just let it die.
                readerThread = null;
            }
        }

        private void ReaderLoop(NetworkStream stream)
        {
            try
            {
                using (var sr = new StreamReader(stream, Utf8NoBom, false, 1024, true))
                {
                    string line;
                    while (!stopRequested && (line = sr.ReadLine()) != null)
                    {
                        line = line.Trim();
                        if (line.Length == 0)
                        {
                            continue;
                        }

                        Console.WriteLine("GtaCopilot: inbound <- " + (line.Length > 120 ? line.Substring(0, 120) + "..." : line));

                        string refuseAck;
                        bool consumed = actionReceiver.ParseAndEnqueue(line, out refuseAck);

                        if (consumed && refuseAck != null)
                        {
                            // Immediate refusal — send ack back right away
                            EnqueueAck(refuseAck);
                        }

                        if (!consumed)
                        {
                            Console.WriteLine("GtaCopilot: unrecognized inbound line (ignored)");
                        }
                    }
                }
            }
            catch (IOException)
            {
                // Stream closed — normal disconnect
            }
            catch (ObjectDisposedException)
            {
                // Stream already disposed — normal shutdown
            }
            catch (Exception ex)
            {
                Console.WriteLine("GtaCopilot: reader error: " + ex.Message);
            }
        }

        private string WaitForNextLine()
        {
            lock (queueLock)
            {
                while (pendingLines.Count == 0)
                {
                    if (stopRequested)
                    {
                        return null;
                    }

                    Monitor.Wait(queueLock);
                }

                if (stopRequested)
                {
                    return null;
                }

                return pendingLines.Dequeue();
            }
        }

        private static void CloseQuietly(ref TcpClient client, ref NetworkStream stream)
        {
            if (stream != null)
            {
                try
                {
                    stream.Dispose();
                }
                catch
                {
                    // Already broken; nothing useful to do.
                }

                stream = null;
            }

            if (client != null)
            {
                try
                {
                    client.Close();
                }
                catch
                {
                    // Already broken; nothing useful to do.
                }

                client = null;
            }
        }
    }
}
